language: python
python:
  - "2.7"
before_script:
  - sudo rm -f /etc/mysql/my.cnf
  - sudo apt-get purge mysql-server mysql-client -y
script: sudo python test/test.py
notifications:
  email: false
  irc: "irc.freenode.net#ssut"

