language: python
env:
  - TRAVIS_CI=1
python:
  - "2.7"
before_script:
  - sudo rm -f /etc/mysql/my.cnf
  - sudo apt-get purge mysql-server mysql-client -y
script: TRAVIS_CI=1 sudo python test/test.py
notifications:
  email: false
  irc: "irc.freenode.net#ssut"

